# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KMLToDXF
                                 A QGIS plugin
 Plugin para converter camadas KML em DXF preservando texto como atributos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-01
        copyright            : (C) 2025 by Desenvolvedor QGIS
        email                : desenvolvedor@email.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KMLToDXF class from file KMLToDXF.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .kml_to_dxf import KMLToDXFPlugin
    return KMLToDXFPlugin(iface)